###############
GPU: [0]
PORT: 4567

MODEL:
  NAME: MSRDAFNet
  MODE: derain
  ARGS:
    in_channels: 3
    out_channels: 3

TRAIN:
  TOTAL_EPOCHS: 4
  BATCH_SIZE: 2
  PRINT_FRE: 50          ## iter frequency of print
  SAVE_FRE:  2000        ## iter frequency of save checkpoints
  VAL_FRE:   150000      ## iter frequency of val
  SAVE_IMG:  true        ## val nseed save images?
  RESUME:    false       ## resume? true or false
  PRETRAIN_MODEL: ~      ## pretrain_model: latested or model_epoch_num

  TRAIN_PS:  256         ## patchsize of train
  VAL_PS:   ~            ## patchsize of val

PATH:
  TRAIN_DATASET: './SPAD_UNZIP/real_world.txt'
  VAL_DATASET: './SPAD/test'

# Optimization arguments.
OPTIM:  #default Adam
  lr: !!float 1e-4
  betas: [0.9, 0.999]
  eps: !!float 1e-8

# schedual arguments.
SCHE:
  T_max: 1276984
  eta_min: !!float 1e-6


