###############
GPU: [0]
PORT: 4567

MODEL:
  NAME: MSRDAFNet
  MODE: deblur    #
  ARGS:
    in_channels: 3
    out_channels: 3

TRAIN:
  TOTAL_EPOCHS: 3000
  BATCH_SIZE: 2
  PRINT_FRE: 40          ## iter frequency of print
  SAVE_FRE:  1           ## epoch frequency of save checkpoints
  VAL_FRE:   200         ## epoch frequency of val
  SAVE_IMG:  false       ## val nseed save images?
  RESUME:    false       ## resume? true or false
  PRETRAIN_MODEL: ~      ## pretrain_model: latested or model_epoch_num
  
  TRAIN_PS: 256          ## patchsize of train
  VAL_PS:  ~             ## patchsize of val

PATH:
  TRAIN_DATASET: './GoPro/train'
  VAL_DATASET: './GoPro/test'

# Optimization arguments.
OPTIM:  #default Adam
  lr: !!float 1e-4
  betas: [0.9, 0.999]
  eps: !!float 1e-8

# Schedual arguments.
SCHE:
  total_iter: 2702.7027027271
